version: "3.2"
services:
  choo-frontend:
    build: choo-frontend
    container_name: choo-frontend
    ports:
      - "2000:5000"
    networks:
      - nginx-network

  choo-backend:
    build: choo-backend
    container_name: choo-backend
    ports:
      - "2100:8080"
    networks:
      - nginx-network

networks:
  nginx-network:
    external: true
